export enum LocalStorageEnum {
  LOCAL_STORAGE_PRIMARY_COLOR_KEY = 'LOCAL_STORAGE_PRIMARY_COLOR_KEY', // primary color
  LOCAL_STORAGE_RECENT_COLORS_KEY = 'LOCAL_STORAGE_RECENT_COLORS_KEY', // recent primary colors
  LOCAL_STORAGE_THEME_KEY = 'LOCAL_STORAGE_THEME_KEY', // theme
  LOCAL_STORAGE_COMPACT_KEY = 'LOCAL_STORAGE_COMPACT_KEY', // compact
  LOCAL_STORAGE_MODE_KEY = 'LOCAL_STORAGE_MODE_KEY', // mode
  LOCAL_STORAGE_LOCALE_KEY = 'LOCAL_STORAGE_LOCALE_KEY', // locale
  LOCAL_STORAGE_BACKGROUND_COLOR_KEY = 'LOCAL_STORAGE_BACKGROUND_COLOR_KEY', // background color
  LOCAL_STORAGE_BACKGROUND_RECENT_COLORS_KEY = 'LOCAL_STORAGE_BACKGROUND_RECENT_COLORS_KEY', // recent background colors
  LOCAL_STORAGE_SORT = 'LOCAL_STORAGE_SORT', // sort type
  LOCAL_STORAGE_IMAGE_SIZE_SCALE = 'LOCAL_STORAGE_IMAGE_SIZE_SCALE', // image scale ratio
  LOCAL_STORAGE_DISPLAY_TYPE = 'LOCAL_STORAGE_DISPLAY_TYPE', // display image type
  LOCAL_STORAGE_DISPLAY_GROUP = 'LOCAL_STORAGE_DISPLAY_GROUP', // display group type
  LOCAL_STORAGE_DISPLAY_STYLE = 'LOCAL_STORAGE_DISPLAY_STYLE', // display style (nested | flat)
}
