export enum localStorageEnum {
  LOCAL_STORAGE_PRIMARY_COLOR_KEY = 'LOCAL_STORAGE_PRIMARY_COLOR_KEY', // 主题色
  LOCAL_STORAGE_RECENT_COLORS_KEY = 'LOCAL_STORAGE_RECENT_COLORS_KEY', // 最新使用的主题色
  LOCAL_STORAGE_LOCALE_KEY = 'LOCAL_STORAGE_LOCALE_KEY', // 语言
  LOCAL_STORAGE_BACKGROUND_RECENT_COLORS_KEY = 'LOCAL_STORAGE_BACKGROUND_RECENT_COLORS_KEY', // 最近使用的背景颜色列表
  LOCAL_STORAGE_BACKGROUND_COLOR_KEY = 'LOCAL_STORAGE_BACKGROUND_COLOR_KEY', // 当前使用的背景颜色
  LOCAL_STORAGE_SORT = 'LOCAL_STORAGE_SORT', // 当前使用的排序方式
  LOCAL_STORAGE_IMAGE_SIZE_SCALE = 'LOCAL_STORAGE_IMAGE_SIZE_SCALE', // 当前使用的图片尺寸
  LOCAL_STORAGE_DISPLAY_TYPE = 'LOCAL_STORAGE_DISPLAY_TYPE', // 展示的图片类型
}
