export enum LocalStorageEnum {
  LOCAL_STORAGE_RECENT_COLORS_KEY = 'LOCAL_STORAGE_RECENT_COLORS_KEY', // recent primary colors
  LOCAL_STORAGE_MODE_KEY = 'LOCAL_STORAGE_MODE_KEY', // mode
  LOCAL_STORAGE_BACKGROUND_RECENT_COLORS_KEY = 'LOCAL_STORAGE_BACKGROUND_RECENT_COLORS_KEY', // recent background colors
  LOCAL_STORAGE_SORT = 'LOCAL_STORAGE_SORT', // sort type
  LOCAL_STORAGE_DISPLAY_TYPE = 'LOCAL_STORAGE_DISPLAY_TYPE', // display image type
  LOCAL_STORAGE_DISPLAY_GROUP = 'LOCAL_STORAGE_DISPLAY_GROUP', // display group type
  LOCAL_STORAGE_DISPLAY_STYLE = 'LOCAL_STORAGE_DISPLAY_STYLE', // display style (nested | flat)
}
