export enum CmdToWebview {
  CallbackFromVscode = 'CallbackFromVscode',

  IMAGES_CHANGED = 'IMAGES_CHANGED',
}

export enum CmdToVscode {
  RELOAD_WEBVIEW = 'RELOAD_WEBVIEW',
  GET_ALL_IMAGES = 'GET_ALL_IMAGES',
  GET_IMAGE_DIMENSIONS = 'GET_IMAGE_DIMENSIONS',
  GET_EXT_CONFIG = 'GET_EXT_CONFIG',
  GET_COMPRESSOR = 'GET_COMPRESSOR',
  OPEN_IMAGE_IN_VSCODE_EXPLORER = 'OPEN_IMAGE_IN_VSCODE_EXPLORER',
  OPEN_IMAGE_IN_OS_EXPLORER = 'OPEN_IMAGE_IN_OS_EXPLORER',
  COPY_IMAGE_AS_BASE64 = 'COPY_IMAGE_AS_BASE64',
  COMPRESS_IMAGE = 'COMPRESS_IMAGE',

  // 测试 vscode 内置命令 for dev convenience
  TEMP_TEST_CMD = 'TEMP_TEST_CMD',
}
