export const CallbackFromVscode = 'CallbackFromVscode'

export enum CmdToVscode {
  RELOAD_WEBVIEW = 'RELOAD_WEBVIEW',
  GET_ALL_IMAGES = 'GET_ALL_IMAGES',
  GET_IMAGE_DIMENSIONS = 'GET_IMAGE_DIMENSIONS',
  GET_EXT_CONFIG = 'GET_EXT_CONFIG',
  COPY_IMAGE = 'COPY_IMAGE',
  PASTE_IMAGE = 'PASTE_IMAGE',
}
